/**
 * Demo/meeting bookings for "Reservar Demo".
 *
 * Firestore collection: `meetings` (or `demo_bookings`)
 *
 * Recommended document structure:
 * - Document ID: auto-generated by Firestore
 * - Query by: scheduledAt (for calendar views), status (pending/confirmed/cancelled)
 *
 * Example queries:
 * - Upcoming: where("scheduledAt", ">=", now), where("status", "==", "confirmed")
 * - By date range: where("scheduledAt", ">=", startOfDay), where("scheduledAt", "<=", endOfDay)
 */
export type MeetingStatus = "pending" | "confirmed" | "cancelled" | "completed";

export interface Meeting {
  id: string;
  /** Simplexa Labs user/admin who hosts the meeting */
  assignedToUserId: string;
  /** Guest / lead who booked the demo */
  guestName: string;
  guestEmail: string;
  guestPhone?: string;
  /** Date and time of the meeting (use Firestore Timestamp when writing) */
  scheduledAt: Date;
  /** Duration in minutes, e.g. 30 (Firestore may use "duration" as field name) */
  durationMinutes: number;
  status: MeetingStatus;
  /** Optional notes from the guest or internal */
  notes?: string;
  /** Source of the booking, e.g. "website", "calendly", "cal.com" */
  source?: string;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Shape for writing to Firestore.
 * - Use serverTimestamp() for createdAt and updatedAt
 * - Use Timestamp.fromDate() for scheduledAt
 *
 * Example:
 *   await addDoc(collection(db, "meetings"), {
 *     guestName, guestEmail, guestPhone,
 *     scheduledAt: Timestamp.fromDate(scheduledDate),
 *     durationMinutes: 30,
 *     status: "pending",
 *     notes, source: "website",
 *     createdAt: serverTimestamp(),
 *     updatedAt: serverTimestamp(),
 *   });
 */
export type MeetingCreate = Omit<
  Meeting,
  "id" | "createdAt" | "updatedAt"
>;
